[package]
name = "iced_blur"
version = "0.1.0"
edition = "2024"
authors = ["Richard Custodio <richardcustodio@pm.me>"]
description = "a blur widget for iced"
license = "MIT"

[workspace]
members = ["examples/*"]

[dependencies]
iced_core = { version = "0.14.0-dev" }
iced_wgpu = { version = "0.14.0-dev" }
iced_widget = { version = "0.14.0-dev", features = ["wgpu"] }
bytemuck = { version = "1.0", features = ["derive"] }

[patch.crates-io]
iced = { git = "https://github.com/B0ney/iced", branch = "paragon" }
iced_wgpu = { git = "https://github.com/B0ney/iced", branch = "paragon" }
iced_core = { git = "https://github.com/B0ney/iced", branch = "paragon" }
iced_widget = { git = "https://github.com/B0ney/iced", branch = "paragon" }
